Camp-Story/campstory-frontend

index.html

카카오 api 연동했습니다.
<br>
카카오 api 연동했습니다.
<br>
<br>
<br>

feat: kakao api

---

README.md

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/9)
readme 오탈자 git run lint -> npm run lint 로 수정하였습니다.
<br>
<br>
<br>
<br>

fix: readme 오탈자 수정

---

src/constants/path.ts

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/6)
path.ts
<br>
evnet -> event로 수정했습니다
<br>
<br>
<br>

rename: event

---

src/pages/CampingMain.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/4)
Camping 메인 페이지 ui 제작했습니다.
<br>
Camping 메인 페이지 ui 제작했습니다.
<br>
<br>
<br>

feat: Camping Main Page UI

---

src/components/layouts/HomeLayout.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/14)
속이 괜찮아 졌어요
<br>
<br>
<br>
<br>

텍스트 수정 속이 아픕니다.

---

README.md

test commit pr
test first!!
<br>
<br>
<br>
<br>

new commit test 2

---

src/pages/CampingMain.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/24#issue-2803210564)
search bar 컴포넌트 추가 했습니다.
<br>
<br>
<br>
<br>

feat: search bar 컴포넌트 제작

---

src/components/layouts/HomeLayout.tsx
src/components/layouts/MainNavigation.tsx
src/pages/Home.tsx
tailwind.config.ts

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/26)
<br>
네비게이션 및 푸터 UI 구현하였고, main 레이아웃에 적용할 커스텀 패딩 값 92px 추가하였습니다.
ex. px-main : padding-left, right 92px
<br>
<br>
<br>

26 네비게이션 푸터 UI 구현

---

src/pages/Home.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/38)
HOME 페이지 축제 섹션 구현
<br>
HOME 페이지 축제 섹션 UI 구현하였습니다.
<br>
<br>
<br>

feat: 축제 섹션 UI 구현

---

src/app/routes/EVENT_ROUTES.tsx
src/components/camping/campingDetail/SpotAboutSection.tsx
src/components/event/eventDetail/DetailLeft.tsx
src/components/event/eventDetail/DetailRight.tsx
src/pages/EventDetail.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/61)
행사 상세 페이지 퍼블리싱을 진행했습니다.
<br>
상단 상세 정보 섹션만 따로 작업한 후 캠핑 상세 페이지에서 사용한 인근 명소와 리뷰 컴포넌트를 조립하는 방식으로 진행했습니다.
상단 상세 정보 섹션은 왼쪽, 오른쪽 article로 나뉩니다.
왼쪽 article은 이미지와 추가 예정인 기능을 다루고,
오른족 article은 상세 정보와 지도 등이 위치합니다.
<br>
<br>
<br>

61 publishing event detail page

---

src/app/routes/AUTH_ROUTES.tsx
src/pages/Login.tsx
src/pages/SignUp.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/62)
Auth_Routes에 로그인, 회원가입 페이지 연결
로그인 페이지 제작
회원가입 페이지 제작
<br>
<br>
<br>
<br>

62 publishing login page

---

src/app/routes/RESTAURANT_ROUTES.tsx
src/components/camping/campingDetail/ImageSection.tsx
src/components/camping/campingDetail/NearbyPlacesSection.tsx
src/pages/RestaurantDetail.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/66)
음식 상세 페이지 퍼블리싱을 진행했습니다.
<br>
행사 상세 페이지에서 props만 수정 후 컴포넌트를 조립하는 방식으로 진행했습니다.
상단 상세 정보 섹션은 왼쪽, 오른쪽 article로 나뉩니다.
왼쪽 article은 이미지와 추가 예정인 기능을 다루고,
오른족 article은 상세 정보와 지도 등이 위치합니다.
<br>
<br>
<br>

66 publishing food detail page

---

src/app/routes/AUTH_MYPAGE_ROUTES.tsx
src/components/mypage/BookmarkCard.tsx
src/pages/Bookmark.tsx

- [GITHUB ISSUE LINK](#71 )
북마크 페이지 제작
컴포넌트에 마이페이지 폴더 추가
북마크 카드 컴포넌트 추가
마이페이지에 북마크 페이지 라우터 연결
<br>
<br>
<br>
<br>

71 publishing mypage bookmark page

---

src/components/shopping/ProductCard.tsx
src/components/shopping/RecommendCard.tsx
src/pages/CampingDetail.tsx
src/pages/ShoppingMain.tsx
src/types/ProductCardProps.ts
src/types/ShoppingProps.ts

- [GITHUB ISSUE LINK](#78)
- ProductCard 컴포넌트 변경으로 깨졌던 쇼핑 메인 페이지 수정했습니다.
- ProductCard 컴포넌트 css를 figma에 맞게 조금 수정해주었습니다.
<br>
석준님께서 만드신 ProductCard 컴포넌트를 기준으로,
ShoppingMain 페이지의 데이터의 값과, 컴포넌트들의 props만 약간 수정해주었습니다. 
css는 글자 색상, 크기, 간격, 이미지 사이즈를 조금 수정했습니다.
<br>
<br>

78 fix ShoppingMain productcard

---

src/app/routes/AUTH_MYPAGE_ROUTES.tsx
src/components/mypage/Post.tsx
src/pages/MypageActivities.tsx

- [GITHUB ISSUE LINK](#83 )
마이페이지 내 게시물 섹션 추가
<br>
<br>
<br>
<br>

feat: 마이페이지 내 게시물 추가가

---

src/app/routes/QUESTION_ROUTES.tsx
src/components/community/QuestionTag.tsx
src/components/community/question/QuestionCard.tsx
src/pages/QuestionMain.tsx

- [GITHUB ISSUE LINK](#86)
커뮤니티 질문 페이지 퍼블리싱 했습니다.
<br>
1. 검색창: SearchInput 컴포넌트 가져와서 재사용 했습니다.
2. 정렬, 태그, 질문 작성하기 버튼
- 정렬: OrderRadio 컴포넌트 가져와서 재사용 했습니다.
- 태그: Tag 컴포넌트 활용하여 QuestionTag 컴포넌트 만들어 활용했습니다.
- 질문 작성하기 버튼: button 태그로 만들었습니다.
3. 질문 카드
- 사용자 정보: UserProfile 컴포넌트 가져와서 재사용했습니다.
- 배지: AdditionalInfo 컴포넌트 가져와서 재사용했습니다.
<br>
<br>
<br>

86 publishing community question page

---

src/components/shopping/ProductCardList.tsx
src/pages/ShoppingSearch.tsx

- [GITHUB ISSUE LINK](#88 )
ShoppingSearch 기존 필터 OderRadio 컴포넌트로 replace했습니다.
<br>
<br>
<br>
<br>

fix: ShoppingSearch 네비게이션바 수정정

---

src/components/home/EventSection.tsx
src/components/home/FoodSection.tsx
src/components/home/ShoppingSection.tsx
src/components/home/TopCampingSpotsSection.tsx
src/components/layouts/MainNavigation.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/90)
- 네비게이션 메뉴의 폰트 사이즈를 키웠습니다.
- 인기 캠핑장 아이템의 기본 이미지를 변경했습니다.
- 각 섹션의 '더보기' 버튼에 path를 지정했습니다.
- 음식 카테고리 아이템에 'key' props를 부여했습니다.
<br>
<br>
<br>
(여기에 데모 화면 스크린샷을 추가하세요)

90 fix add key prop to foodcategoryitem component

---

src/components/event/CardButton.tsx
src/components/event/EventCalendarSection.tsx
src/components/event/EventCategoryCard.tsx
src/components/event/SearchBar.tsx
src/components/event/SubTitle.tsx
src/components/event/TodaySection.tsx
src/pages/EventMain.tsx
src/types/EventCalendarSectionProps.ts
src/types/TodaySectionProps.ts

- [GITHUB ISSUE LINK](#84 )
메인 검색창 수정
메인 카테고리 수정
메인 오늘의 추천행사 수정
<br>
<br>
<br>
<br>

84 fix event main page

---

src/app/routes/AUTH_MYPAGE_ROUTES.tsx
src/pages/ReservedList.tsx

마이페이지 예약내역 리스트 
<br>
마이페이지 예약내역 리스트 추가
<br>
<br>
<br>

mypage  reservedList page

---

src/app/routes/QUESTION_ROUTES.tsx
src/components/community/QuestionTag.tsx
src/components/community/UserProfile.tsx
src/components/community/question/Comment.tsx
src/components/community/question/CommentInput.tsx
src/components/community/question/QuestionCard.tsx
src/components/community/question/QuestionDetailCard.tsx
src/pages/QuestionDetail.tsx
src/pages/QuestionMain.tsx

- [GITHUB ISSUE LINK](#93)
QuestionMain Page css 조금 수정하고, Question 상세 페이지 퍼블리싱 했습니다.
<br>
**1. QuestionMain Page css 수정 </span>**
- QuestionCard border radius 추가
- QuestionCard font weight 수정
- QuestionTag text color 변경
**2. QuestionDetailCard 컴포넌트 생성**
- QuestionCard 컴포넌트를 활용하여 다시 만들었습니다.
**3. CommentInput 컴포넌트 생성**
- SearchBar 컴포넌트를 활용하여 버튼 아이콘과 너비를 수정하여 다시 만들었습니다.
**4. Comment 컴포넌트 생성**
<br>

93 publishing question detail page

---

src/app/routes/QUESTION_ROUTES.tsx
src/components/community/question/QuestionCreate/InputContainer.tsx
src/pages/QudstionCreate.tsx
src/pages/QuestionDetail.tsx
src/pages/QuestionModify.tsx

- #97 
질문 생성 및 수정 페이지 퍼블리싱
<br>
미리님 pr 풀 받아서 수정했습니다.
<br>
<br>
<br>

97 publishing qeustion create page

---

src/components/shopping/ProductCard.tsx
src/components/shopping/ProductCardList.tsx
src/pages/ShoppingSearch.tsx
src/types/ProductCardProps.ts

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/108)
쇼핑 검색 페이지에 NAVER API 연동하여 쇼핑 검색 목록을 구혆하였고, 정렬 기능을 추가하였습니다.
<br>
<br>
<br>
<br>

108 shopping search page   implement product retrieval api integration

---

src/components/common/SearchInput.tsx
src/pages/RestaurantSearch.tsx

- [GITHUB ISSUE LINK](#107 )
Common Search 컴포넌트에서 SearchInput 코드 검색활용할수있게 리팩토링 하였습니다.
SearchInput 컴포넌트 이용하여 RestaurantSearch 페이지에서 검색 가능 하게 만들었습니다.
기본 검색 설정은 keyword "서울"로 셋팅했습니다
<br>
<br>
<br>
<br>

107 connect api to the restaurant search page

---

src/components/event/EventCategoryCard.tsx
src/components/event/TodaySection.tsx
src/pages/EventMain.tsx
src/pages/EventSearch.tsx
src/types/TodaySectionProps.ts

- [GITHUB ISSUE LINK](#118 )
행사 메인 페이지에서 카테고리를 통해 검색 페이지 검색 추가
행사 검색 페이지에서 검색을 통해 목록 필터링 추가
행사 메인 페이지에서 추천 행사 섹션을 통해 해당 상세 페이지로 넘어가지는 기능 추가
<br>
<br>
<br>
<br>

118 connect event search api

---

src/app/routes/RESTAURANT_ROUTES.tsx
src/components/common/search/CategoryCheckbox.tsx
src/components/common/search/CheckboxList.tsx
src/components/detail/DetailRight.tsx
src/components/food/CategoryMap.ts
src/components/food/RestaurantMain/Banner.tsx
src/components/food/RestaurantMain/CategoryCard.tsx
src/components/food/RestaurantMain/SearchBar.tsx
src/components/food/RestaurantMain/Title.tsx
src/components/food/RestaurantMain/TodaysPick.tsx
src/pages/RestaurantDetail.tsx
src/pages/RestaurantMain.tsx
src/pages/RestaurantSearch.tsx

필터,상세 페이지 
메인에서 검색시 search페이지에서 바로 렌더링
<br>
<br>
<br>
<br>

114 connect api to the restaurantinfo page

---

components.json
package-lock.json
package.json
src/index.css
src/lib/utils.ts
tailwind.config.ts
tsconfig.json

- #122 
shadcn 설치 및 세팅
<br>
<br>
<br>
<br>

install shadcn

---

src/components/common/SearchInput.tsx
src/components/common/main/SearchBar.tsx
src/components/common/search/SearchCard.tsx
src/components/layouts/MainNavigation.tsx
src/components/layouts/RootLayout.tsx
src/components/shopping/Category.tsx
src/components/shopping/CategoryCard.tsx
src/components/shopping/ProductCard.tsx
src/components/shopping/ProductCardList.tsx
src/components/shopping/RecommendCard.tsx
src/pages/ShoppingMain.tsx
src/pages/ShoppingSearch.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/119)
- 카테고리 관련 컴포넌트에 `onClick` 메서드 추가
- `RecommendCard` 스타일 업데이트
- `ProductCardList`의 일부 로직 수정
- `SearchCard` 컴포넌트의 스타일 업데이트
- `ShoppingMain`에 카테고리 기반 네비게이션 및 검색 로직 추가
- 검색 및 정렬을 위한 URL 파라미터 변경 로직 추가 및 수정
- `SearchInput`과 `SearchBar`에 검색 기능 및 keydown 이벤트 핸들러 추가
- 헤더 내 네비게이션 바 스타일 업데이트
- 상태(state)에서 참조(ref)로 로직 변경
---
- `onClick` 메서드를 카테고리 관련 컴포넌트에 추가하여 사용자 인터페이스의 상호작용성을 개선함.
- `RecommendCard`, `SearchCard` 및 네비게이션 바의 스타일을 업데이트하여 UI/UX 개선.
- `ShoppingMain`에 카테고리 기반 네비게이션 및 검색 기능을 추가해 사용자 경험 향상.
- URL 파라미터를 통한 검색 및 정렬 로직을 추가하여 URL을 통한 상태 관리 가능.
- `SearchInput`과 `SearchBar`에 검색 기능과 keydown 이벤트 핸들러를 추가하여 사용자 편의성 향상.
- 상태를 참조로 변경하여 성능 최적화.
---
- UI/UX 개선이 필요한 부분은 없는지 확인
- URL 파라미터와 관련된 로직에 문제가 없는지 확인
- 이벤트 핸들러 및 기능 …

119 implement shopping search and category features

---

package-lock.json
package.json
src/components/home/BannerSection.tsx
src/components/ui/select.tsx

- [GITHUB ISSUE LINK](#125 )
Home page에서 캠핑 검색 기능 구현 했습니다.
<br>
<br>
<br>
<br>

125 home page search

---

src/components/community/Tag.tsx
src/components/community/community/AreaCard.tsx
src/components/community/question/CommentInput.tsx
src/components/community/question/QuestionCard.tsx
src/components/community/question/QuestionDetailCard.tsx
src/pages/CommunityDetail.tsx
src/pages/CommunityMain.tsx
src/pages/QuestionDetail.tsx
src/pages/QuestionMain.tsx

- [GITHUB ISSUE LINK](https://github.com/Camp-Story/campstory-frontend/issues/130)
- 커뮤니티 및 질문 페이지 UI 일부 수정  
- 네비게이션 바 페이지 가운데 정렬  
---
- **커뮤니티 메인 페이지** 및 **상세 페이지** UI 개선  
- **질문 메인 페이지** 및 **상세 페이지** UI 수정  
- **네비게이션 바 가운데 정렬**을 통해 레이아웃 정리 및 가독성 향상  
---
- UI 수정 후 레이아웃이 정상적으로 적용되는지 확인  
- 네비게이션 바 정렬이 올바르게 반영되었는지 검토  
- 기존 기능에 영향을 주는 변경 사항이 없는지 테스트  
---
(스크린샷 또는 GIF 포함)

130 community page UI redesign and improvements

---

src/components/detail/DetailRight.tsx
src/components/event/EventAreaCheckbox.tsx
src/components/event/EventCategoryCard.tsx
src/components/event/EventCategoryMap.ts
src/components/event/SearchBar.tsx
src/constants/filters.ts
src/pages/EventDetail.tsx
src/pages/EventMain.tsx
src/pages/EventSearch.tsx
src/types/EventResponse.ts

- [GITHUB ISSUE LINK](#128  )
행사 메인 페이지에서 검색 기능 추가했습니다.
행사 검색 페이지에서 카테고리 기능 행사 종류별, 지역별 필터 추가했습니다.
행사 상세 페이지에서 행사 장소, 행사 기간, 홈페이지 들어가게 했습니다.
<br>
<br>
<br>
<br>

128 event main page search page filter

---

src/components/event/Banner.tsx
src/components/event/SearchBar.tsx
src/components/food/RestaurantMain/Banner.tsx
src/components/food/RestaurantMain/CategoryCard.tsx
src/components/food/RestaurantMain/SearchBar.tsx
src/components/food/RestaurantMain/TodaysPick.tsx
src/components/food/RestaurantSearch/CategoryCheckbox.tsx
src/components/food/RestaurantSearch/CheckboxList.tsx
src/pages/RestaurantDetail.tsx
src/pages/RestaurantMain.tsx
src/pages/RestaurantSearch.tsx
src/pages/SignUp.tsx

다중필터,
음식,행사 메인 검색창 길이 수정.
<br>
<br>
<br>
<br>

123 refactoring filter on the restaurant main page

---

src/app/router.tsx
src/components/layouts/AuthMyPageLayout.tsx
src/components/layouts/MainNavigation.tsx
src/components/layouts/RootLayout.tsx
src/components/mypage/MyPost.tsx
src/components/mypage/MyQuestion.tsx
src/components/ui/InputField.tsx
src/constants/path.ts
src/hooks/useForm.ts
src/pages/CommunityMain.tsx
src/pages/Login.tsx
src/pages/MypageActivities.tsx
src/pages/MypageInfo.tsx
src/pages/Sample.tsx
src/pages/SignUp.tsx
src/service/fetchWeatherData.ts
src/types/AuthResponse.ts
src/utils/FormValidator.ts
src/utils/KmaCoordConverter.ts
src/utils/authToken.ts
src/utils/axiosInstance.ts
src/utils/fetchWeatherData.ts
src/vite-env.d.ts

- [GITHUB ISSUE LINK](#136 )
날씨 API 사용 로직을 추가하고, 로그인•회원가입 기능에 유효성 검사 로직을 추가하여 리팩터링 진행하였습니다.
토큰 관련 로직을 추가하여 로그인 상태를 관리하도록 변경하였습니다.
<br>
<br>
<br>
<br>

136 weather api integration testing

---

src/pages/CampingSearch.tsx

캠핑 검색 페이지에서 무한 스크롤 기능 구현 했습니다.
<br>
<br>
<br>
<br>

133 campingsearch infinite scroll

---

src/app/router.tsx
src/components/detail/DetailRight.tsx
src/components/detail/ProductInfo.tsx
src/components/layouts/MainNavigation.tsx
src/components/layouts/RootLayout.tsx
src/constants/path.ts
src/pages/CampingSearch.tsx
src/pages/Logout.ts

- [GITHUB ISSUE LINK](#140 )
누락된 로그아웃 기능 변경사항 업데이트 하였습니다.
<br>
<br>
<br>
<br>

140 add missing logout functionality

---

src/components/event/Banner.tsx
src/components/event/CalendarEventCard.tsx
src/components/event/EventCalendarSection.tsx
src/components/event/EventCategoryCard.tsx
src/components/event/SubTitle.tsx
src/components/event/TodaySection.tsx
src/components/food/RestaurantMain/Banner.tsx
src/components/food/RestaurantMain/CategoryCard.tsx
src/components/food/RestaurantMain/Title.tsx
src/components/food/RestaurantMain/TodaysPick.tsx
src/pages/EventMain.tsx
src/pages/RestaurantMain.tsx
src/types/CalendarEventCardProps.ts

- [GITHUB ISSUE LINK](#135 )
행사 메인 페이지 캘린더 섹션 행사 목록에 api 연동했습니다.
행사 메인 페이지 css 수정했습니다.
음식 메인 페이지 css 수정했습니다.
<br>
<br>
<br>
<br>

135 event main page calendar event search page date filter

---

src/components/common/search/SearchCard.tsx
src/hooks/useAuth/AuthContext.tsx
src/hooks/useAuth/AuthProvider.tsx
src/hooks/useBookmark.ts
src/pages/CampingSearch.tsx
src/pages/EventSearch.tsx
src/pages/RestaurantSearch.tsx
src/types/AuthResponse.ts
src/types/ChannelResponse.ts

- #151 
북마크 기능 구현 중
<br>
북마크 기능을 구현했습니다.
찜하기, 해제 둘 다 기능은 동작하지만 새로고침을 해야 화면에 표시되는 문제가 있어서 그 문제를 해결하고 있습니다.
추가적으로 새로고침 과정에서 context의 유저 정보가 사라지는 문제가 발견되어서 해결을 위해 id를 localstorage에 저장했습니다.
<br>
<br>
<br>

151 apply bookmark

---

src/components/community/Tag.tsx
src/components/community/TagList.tsx
src/components/community/community/CommunityDetail/CommunityInput.tsx
src/components/community/community/PostCard.tsx
src/components/community/community/communityCreate/ImageUploader.tsx
src/components/community/question/Comment.tsx
src/components/community/question/CommentInput.tsx
src/components/event/EventAreaCheckbox.tsx
src/constants/channelId.ts
src/pages/CommunityCreate.tsx
src/pages/CommunityDetail.tsx
src/pages/CommunityMain.tsx
src/pages/CommunityModify.tsx
src/utils/getRelativeTime.ts

- [GITHUB ISSUE LINK](#141 )
-커뮤니티 게시물 포스트 작성 및  수
-커뮤니티 게시물 필터
-커뮤니티 게시물 상세 
-커뮤니티 게시물 상세 댓글 작성 및 불러오기
<br>
<br>
<br>
<br>

141 community posting post page

---

src/pages/CommunityDetail.tsx
src/pages/CommunityModify.tsx

- [GITHUB ISSUE LINK](#176 )
수정페이지에서 태그 수정 안되던것 해결했습니다.
<br>
<br>
<br>
<br>

fix: showing tags on the edit page

---

package-lock.json
package.json
src/components/community/question/Comment.tsx
src/components/community/question/CommentInput.tsx
src/components/community/question/QuestionDetailCard.tsx
src/pages/CommunityDetail.tsx
src/pages/QuestionDetail.tsx
src/pages/QuestionMain.tsx
src/types/PostResponse.ts
src/utils/getRelativeTime.ts

- [GITHUB ISSUE LINK](#180 )
-질문 게시판에서 댓글 작성 및 삭제기능 완료했습니다.
-질문 게시판에서도 글 작성시간 보이게 수정했습니다.
-커뮤니티 상세, 페이지 유저 프로필사진 보이게 수정했습니다.
<br>
<br>
<br>
<br>

180 add comment on the questionpage

---

src/components/mypage/MyPost.tsx
src/components/mypage/MyQuestion.tsx
src/pages/MypageActivities.tsx
src/pages/QuestionDetail.tsx
src/pages/QuestionMain.tsx
src/types/PostResponse.ts

- [GITHUB ISSUE LINK](#185)
마이페이지 나의 활동 페이지에 커뮤니티 데이터와 질문 데이터 연동해주었습니다.
css 깨지는 것들 수정해주었습니다.
<br>
<br>
<br>
<br>

185 mypage activities community data

---

src/components/event/CalendarEventCard.tsx
src/components/event/EventCalendarSection.tsx
src/components/layouts/RootLayout.tsx

- #199 
- 캘린더 섹션 UI 수정  
- 내비게이션 패딩 조정  
<br>
- 캘린더 섹션의 디자인을 개선하여 가독성과 UI 일관성을 높임  
- 내비게이션 패딩을 조정하여 레이아웃을 더 균형 있게 정리함  
<br>
- 캘린더 섹션 UI가 적절하게 개선되었는지 확인  
- 내비게이션 패딩 조정이 레이아웃에 잘 적용되었는지 점검  
<br>

199 event page modify UI

---

src/components/detail/WeatherSection.tsx
src/components/event/Calendar.tsx
src/components/event/CalendarEventCard.tsx
src/index.css

- [GITHUB ISSUE LINK](#207 )
상세 페이지 날씨 섹션 최저기온, 최고기온 폰트 색깔 바꿨습니다.
행사 메인 페이지 캘린더 영역 임시로 index.css로 스타일 변경했습니다.
행사 메인 페이지 캘린더 영역 행사 카드 border 색 수정했습니다. 
<br>
<br>
<br>
<br>

207 weathersection color fix

---

package-lock.json
src/components/community/AdditionalInfo.tsx
src/components/community/Badge.tsx
src/components/community/community/PostCard.tsx
src/components/community/question/QuestionCard.tsx
src/components/community/question/QuestionDetailCard.tsx
src/hooks/useLike.ts
src/pages/CommunityDetail.tsx
src/pages/CommunityMain.tsx
src/pages/QuestionMain.tsx
src/types/PostResponse.ts

- [GITHUB ISSUE LINK](#189 )
커뮤니티, 질문 게시판
-좋아요 기능 추가하였습니다.
-공유하기, 북마크 아이콘은 제거하였습니다.
-인기순으로 필터링기능 추가되었습니다.
-viewCount는 Math.random 함수로 구현하였습니다. 
<br>
ViewCount는useMemo를 사용하여  처음 마운트 될 때 한번만 계산되게끔 수정하였습니다.
<br>
<br>
<br>

189 finding some bugs then fix

---

src/components/shopping/ProductInfo.tsx
src/pages/EventSearch.tsx
src/pages/RestaurantSearch.tsx

- [GITHUB ISSUE LINK](#210 )
쇼핑 상세 페이지 버튼 활성화 했습니다.
검색 페이지 검색 결과 텍스트 통일했습니다.
<br>
<br>
<br>
<br>

210 eventsearchpage filter
